version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: reactjs-client
    container_name: ${PROJECT_NAME}-client
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: yarn start

volumes:
  pgdata:
  node_modules:

  # Documentação usada para a construção desse arquivo
  # https://www.digitalocean.com/community/tutorials/containerizing-a-node-js-application-for-development-with-docker-compose-pt
  # (principalmente o passo 4)
